### ISSUE TITLE
Font / Colorscheme

### ISSUE THREAD

**Issue by jacobduncan00** [tjdevries/cyclist.vim#2]
What font and colorscheme are used in the readme snapshot?

**Comment by tjdevries** [comment]
It's a custom colorscheme I wrote: https://github.com/tjdevries/gruvbuddy.nvim

The font is JetBrains Mono (I think)

**Comment by tjdevries** [comment]
I added the info to the README. Does that answer what you were wondering?

**Comment by tjdevries** [comment]
I'll close, assuming it did 😂
